plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.portswigger.burp.extender:burp-extender-api:2.3'
}

sourceCompatibility = '17'
targetCompatibility = '17'

jar {
    archiveFileName = 'BurpNakeConnector.jar'
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
